#font_family             JetBrainsMono Nerd Font*/
#bold_font               JetBrains Mono Bold Nerd Font Complete*/
#italic_font             JetBrains Mono Italic Nerd Font Complete*/
#bold_italic_font        JetBrains Mono Bold Italic Nerd Font Complete*/

font_family             Sauce Code Pro Semibold Nerd Font Complete 
bold_font               Sauce Code Pro Bold Nerd Font Complete 
italic_font             Sauce Code Pro Italic Nerd Font Complete 
bold_italic_font        Sauce Code Pro Bold Italic Nerd Font Complete 


font_size               24

#--------------------------------------------------------------------
# Settings
#--------------------------------------------------------------------

update_check_interval   0
enable_audio_bell       no
allow_remote_control    yes
strip_trailing_spaces   smart
mouse_hide_wait         3.0
open_url_with           default
copy_on_select          yes
sync_to_monitor         yes
inactive_text_alpha     0.9
linux_display_server    auto

#--------------------------------------------------------------------
# Key bindings
#--------------------------------------------------------------------
# Clipboard
map super+v             paste_from_clipboard
map super+c             copy_or_interrupt

# Screen
map super+k combine : clear_terminal scroll active : send_text normal,application \x0c

# Miscellaneous
map super+equal      increase_font_size
map super+minus    decrease_font_size
map super+0 restore_font_size

#--------------------------------------------------------------------
# Theme
#--------------------------------------------------------------------
# Nord Colorscheme for Kitty
# Based on:
# - https://gist.github.com/marcusramberg/64010234c95a93d953e8c79fdaf94192
# - https://github.com/arcticicestudio/nord-hyper

foreground            #D8DEE9
background            #2E3440
selection_foreground  #000000
selection_background  #FFFACD
url_color             #0087BD
cursor                #81A1C1

# black
color0   #3B4252
color8   #4C566A

# red
color1   #BF616A
color9   #BF616A

# green
color2   #A3BE8C
color10  #A3BE8C

# yellow
color3   #EBCB8B
color11  #EBCB8B

# blue
color4  #81A1C1
color12 #81A1C1

# magenta
color5   #B48EAD
color13  #B48EAD

# cyan
color6   #88C0D0
color14  #8FBCBB

# white
color7   #E5E9F0
color15  #ECEFF4
