# modules/nixos/desktop-hyprland.nix -- declarative Hyprland desktop
#
# /etc/xdg/hypr/hyprland.lua is a generated header plus the five checked-in
# files in modules/nixos/hypr, concatenated in the order envs, input,
# looknfeel, windows, bindings. The header carries the monitor line, the
# cursor, the exec-once block and the `theme` table the Lua files read, so no
# colour or program name is written in Lua.
#
# Config format: Lua only. hyprlang (.conf) is deprecated since 0.55 and goes
# away in 0.57, and this fleet auto-upgrades from the lockfile.
#
# Sources (all read against the pinned v0.56.2, 2026-09-02):
#   - https://hypr.land/news/26_lua/ -- "if you don't have a hyprland.lua config
#     file, your old hyprland.conf will be loaded [...] if you do have one,
#     hyprland.lua will be loaded instead", checked once at startup.
#   - https://wiki.hypr.land/Configuring/Start/ and the shipped example config
#     Hyprland/example/hyprland.lua (v0.56.2) -- the hl.* API used below.
#   - src/config/supplementary/jeremy/Jeremy.cpp + hyprutils src/path/Path.cpp:
#     findConfig(name, ext) walks XDG_CONFIG_HOME -> ~/.config -> XDG_CONFIG_DIRS
#     -> /etc/xdg, and Jeremy runs that walk for "lua" *entirely* before "conf".
#     So /etc/xdg/hypr/hyprland.lua is a supported system-wide location -- but
#     note it now outranks a user's ~/.config/hypr/hyprland.conf. To take the
#     config over, a user must create ~/.config/hypr/hyprland.lua.
#   - src/config/lua/bindings/LuaBindingsConfigRules.cpp (hl.monitor fields),
#     LuaBindingsToplevel.cpp (hl.bind key string is split on '+' and trimmed;
#     hl.exec_cmd spawns via /bin/sh -c, so `&&` still works),
#     LuaEventHandler.cpp ("hyprland.start" is its own event, distinct from
#     "config.reloaded" -- that is what makes it exec-once and not exec).
#   - src/config/values/ConfigValues.cpp: cursor:no_hardware_cursors is an int
#     (0/1/2); LuaConfigInt::parse casts a Lua boolean to 0/1, so `true` here
#     means the same thing it did in the .conf.

{
  lib,
  config,
  pkgs,
  ...
}:

with lib;
let
  cfg = config.modules.nixos.desktop;

  # Lua string literal. Handles the quoting/escaping the Nix values do not.
  luaStr = builtins.toJSON;

  # `monitor` stays the hyprlang 4-field `output,mode,position,scale` line: it
  # is the shape vm-guest.nix's resize follower re-emits, so one option feeds
  # both.
  monitorFields = splitString "," cfg.monitor;

  themeData = (import ../../lib/theme.nix { inherit pkgs; }) cfg.theme.name;

  # Flat attrset -> a one-line Lua table literal. Only used for colours.
  luaTable =
    attrs: "{ " + concatStringsSep ", " (mapAttrsToList (k: v: "${k} = ${luaStr v}") attrs) + " }";

  execOnce = [
    # Hand the session to systemd: greetd-launched Hyprland does not activate
    # graphical-session.target by itself, and user units WantedBy it (wayvnc)
    # otherwise stay dead. DISPLAY is for user units that talk to XWayland.
    "dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE && systemctl --user start hyprland-session.target"
  ]
  ++ cfg.extraExecOnce;

  # `theme` and `rgba` are Lua globals on purpose: the checked-in files in
  # modules/nixos/hypr are plain chunks appended below this header, and a local
  # would not reach them.
  luaHeader = ''
    -- Generated by modules/nixos/desktop-hyprland.nix from themes/${themeData.name}.
    -- Copy to ~/.config/hypr/hyprland.lua to take it over (a user .conf will
    -- NOT win over this file; Hyprland looks for every .lua before any .conf).
    theme = {
        name = ${luaStr themeData.name},
        mode = ${luaStr themeData.mode},
        cursor_size = ${toString cfg.theme.cursorSize},
        scale = ${luaStr (elemAt monitorFields 3)},
        terminal = ${luaStr cfg.terminal},
        launcher = ${luaStr cfg.launcher},
        colors = ${luaTable themeData.colors},
    }

    -- Palette entries are "#rrggbb" and Hyprland wants "rgba(rrggbbaa)".
    function rgba(hex, alpha) return "rgba(" .. hex:sub(2) .. alpha .. ")" end

    hl.monitor({
        output   = ${luaStr (elemAt monitorFields 0)},
        mode     = ${luaStr (elemAt monitorFields 1)},
        position = ${luaStr (elemAt monitorFields 2)},
        scale    = ${luaStr (elemAt monitorFields 3)},
    })

    hl.config({
        cursor = {
            -- aquamarine ignores WLR_NO_HARDWARE_CURSORS; this is the replacement.
            no_hardware_cursors = true,
        },
    })

    -- hyprland.start fires once per compositor launch (a config reload raises
    -- config.reloaded instead), so this is the exec-once equivalent.
    hl.on("hyprland.start", function()
    ${concatMapStringsSep "\n" (c: "    hl.exec_cmd(${luaStr c})") execOnce}
    end)
  '';

  luaFiles = [
    "envs.lua"
    "input.lua"
    "looknfeel.lua"
    "windows.lua"
    "bindings.lua"
  ];

  luaConfig =
    luaHeader
    + concatMapStringsSep "\n" (f: "\n-- ${f}\n" + builtins.readFile (./hypr + "/${f}")) luaFiles;
in
{
  imports = [ ./desktop-theme.nix ];

  options.modules.nixos.desktop = {
    monitor = mkOption {
      type = types.str;
      default = "Virtual-1,preferred,auto,1";
      description = "Monitor as the hyprlang `output,mode,position,scale` line. Pinned because virtio-gpu reports no EDID, so there is no mode list to negotiate.";
    };

    terminal = mkOption {
      type = types.str;
      default = "alacritty";
      description = "Terminal launched by the Hyprland keybind. Alacritty (GL 3.3) renders on virgl; Ghostty >= 1.2 needs GL 4.3, which Parallels does not give Linux guests.";
    };

    launcher = mkOption {
      type = types.str;
      default = "vicinae toggle";
      description = "Command the launcher keybind runs. Reaches the Lua through the generated theme table, so bindings.lua names no program. vicinae comes from home/linux/desktop/launcher.nix, which also keeps fuzzel installed as the fallback.";
    };

    extraExecOnce = mkOption {
      type = types.listOf types.str;
      default = [ ];
      description = "Extra commands run once at compositor start. Lets guest/hardware modules add session autostarts without this module knowing about them.";
    };

    greeting = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "Text tuigreet shows above the login box. The fire drill host uses it to say that its console accepts no login.";
    };
  };

  config = {
    assertions = [
      {
        assertion = length monitorFields == 4;
        message = "modules.nixos.desktop.monitor must be `output,mode,position,scale`; got ${cfg.monitor}";
      }
    ];

    # Hyprland 0.56 ships no systemd session target, so define the one the
    # exec-once above starts. Binding graphical-session.target lets user units
    # WantedBy it (wayvnc) start with the compositor and stop with it.
    systemd.user.targets.hyprland-session = {
      unitConfig = {
        Description = "Hyprland compositor session";
        Documentation = [ "man:systemd.special(7)" ];
        BindsTo = [ "graphical-session.target" ];
        Wants = [ "graphical-session-pre.target" ];
        After = [ "graphical-session-pre.target" ];
      };
    };

    # Retina through Fusion hands the guest 2x pixels, so the cursor follows the
    # monitor scale. Any other scale keeps the theme module's 24.
    modules.nixos.desktop.theme.cursorSize = mkDefault (
      if elemAt monitorFields 3 == "2" then 32 else 24
    );

    programs.hyprland.enable = true;

    services.greetd = {
      enable = true;
      settings.default_session = {
        command = "${lib.getExe pkgs.tuigreet} --time --remember${
          optionalString (cfg.greeting != null) " --greeting ${escapeShellArg cfg.greeting}"
        } --cmd ${config.programs.hyprland.package}/bin/start-hyprland";
        user = "greeter";
      };
    };

    # The session's auth agent is home-manager's hyprpolkitagent
    # (home/linux/desktop/polkit.nix), which needs the daemon running.
    security.polkit.enable = true;

    # Lockers get their own PAM services. programs.hyprlock would do this too,
    # but it also force-enables the system hypridle unit, and idle has one
    # owner here, home-manager's services.hypridle.
    security.pam.services.hyprlock = { };
    security.pam.services.swaylock = { };

    security.rtkit.enable = true;
    services.pipewire = {
      enable = true;
      alsa.enable = true;
      pulse.enable = true;
    };

    # config/alacritty/alacritty.toml asks for this family by name.
    fonts.packages = [ pkgs.nerd-fonts.jetbrains-mono ];

    environment.systemPackages = with pkgs; [
      # home/shell/alacritty.nix ships config only (the binary comes from the
      # distro on the other Linux hosts), so NixOS has to provide the binary.
      alacritty
      wl-clipboard
      mesa-demos # glxinfo -B is the GPU acceptance check
    ];

    # /etc/xdg is the last stop in hyprutils' config search, so a user config
    # of the same format still wins if one is created.
    environment.etc."xdg/hypr/hyprland.lua".text = luaConfig;
  };
}
