# modules/nixos/desktop-hyprland.nix -- minimal declarative Hyprland desktop
#
# Deliberately small: greetd -> Hyprland, PipeWire, a bar, a notifier, a
# launcher and a terminal. The Omarchy tracked-input port is its own later
# phase and will replace most of this.
#
# Config format: Lua. hyprlang (.conf) is deprecated since 0.55 and 0.56 warns
# on every launch that it goes away in 0.57, and this fleet auto-upgrades from
# the lockfile -- so the .conf renderer is kept only as a one-line revert
# (modules.nixos.desktop.configFormat = "conf").
#
# Sources (all read against the pinned v0.56.2, 2026-09-02):
#   - https://hypr.land/news/26_lua/ -- "if you don't have a hyprland.lua config
#     file, your old hyprland.conf will be loaded [...] if you do have one,
#     hyprland.lua will be loaded instead", checked once at startup.
#   - https://wiki.hypr.land/Configuring/Start/ and the shipped example config
#     Hyprland/example/hyprland.lua (v0.56.2) -- the hl.* API used below.
#   - src/config/supplementary/jeremy/Jeremy.cpp + hyprutils src/path/Path.cpp:
#     findConfig(name, ext) walks XDG_CONFIG_HOME -> ~/.config -> XDG_CONFIG_DIRS
#     -> /etc/xdg, and Jeremy runs that walk for "lua" *entirely* before "conf".
#     So /etc/xdg/hypr/hyprland.lua is a supported system-wide location -- but
#     note it now outranks a user's ~/.config/hypr/hyprland.conf. To take the
#     config over, a user must create ~/.config/hypr/hyprland.lua.
#   - src/config/lua/bindings/LuaBindingsConfigRules.cpp (hl.monitor fields),
#     LuaBindingsToplevel.cpp (hl.bind key string is split on '+' and trimmed;
#     hl.exec_cmd spawns via /bin/sh -c, so `&&` still works),
#     LuaEventHandler.cpp ("hyprland.start" is its own event, distinct from
#     "config.reloaded" -- that is what makes it exec-once and not exec).
#   - src/config/values/ConfigValues.cpp: cursor:no_hardware_cursors is an int
#     (0/1/2); LuaConfigInt::parse casts a Lua boolean to 0/1, so `true` here
#     means the same thing it did in the .conf.

{
  lib,
  config,
  pkgs,
  ...
}:

with lib;
let
  cfg = config.modules.nixos.desktop;

  # Lua string literal. Handles the quoting/escaping the Nix values do not.
  luaStr = builtins.toJSON;

  # `monitor` stays the hyprlang 4-field line so both renderers read one option.
  monitorFields = splitString "," cfg.monitor;

  execOnce = [
    # Hand the session to systemd: greetd-launched Hyprland does not activate
    # graphical-session.target by itself, and user units WantedBy it (wayvnc)
    # otherwise stay dead.
    "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE && systemctl --user start hyprland-session.target"
    "waybar"
    "mako"
  ]
  ++ cfg.extraExecOnce;

  luaConfig = ''
    -- Generated by modules/nixos/desktop-hyprland.nix -- copy to
    -- ~/.config/hypr/hyprland.lua to take it over (a user .conf will NOT win
    -- over this file; Hyprland looks for every .lua before any .conf).

    hl.monitor({
        output   = ${luaStr (elemAt monitorFields 0)},
        mode     = ${luaStr (elemAt monitorFields 1)},
        position = ${luaStr (elemAt monitorFields 2)},
        scale    = ${luaStr (elemAt monitorFields 3)},
    })

    hl.config({
        cursor = {
            -- aquamarine ignores WLR_NO_HARDWARE_CURSORS; this is the replacement.
            no_hardware_cursors = true,
        },
    })

    -- hyprland.start fires once per compositor launch (a config reload raises
    -- config.reloaded instead), so this is the exec-once equivalent.
    hl.on("hyprland.start", function()
    ${concatMapStringsSep "\n" (c: "    hl.exec_cmd(${luaStr c})") execOnce}
    end)

    local mod = "SUPER"
    hl.bind(mod .. " + Return",    hl.dsp.exec_cmd(${luaStr cfg.terminal}))
    hl.bind(mod .. " + D",         hl.dsp.exec_cmd("fuzzel"))
    hl.bind(mod .. " + Q",         hl.dsp.window.close())
    hl.bind(mod .. " + SHIFT + E", hl.dsp.exit())
  '';

  confConfig = ''
    # Generated by modules/nixos/desktop-hyprland.nix -- copy to
    # ~/.config/hypr/hyprland.conf to take it over.
    monitor = ${cfg.monitor}

    cursor {
      # aquamarine ignores WLR_NO_HARDWARE_CURSORS; this is the replacement.
      no_hardware_cursors = true
    }

    ${concatMapStringsSep "\n" (c: "exec-once = ${c}") execOnce}

    $mod = SUPER
    bind = $mod, Return, exec, ${cfg.terminal}
    bind = $mod, D, exec, fuzzel
    bind = $mod, Q, killactive
    bind = $mod SHIFT, E, exit
  '';
in
{
  options.modules.nixos.desktop = {
    configFormat = mkOption {
      type = types.enum [
        "lua"
        "conf"
      ];
      default = "lua";
      description = "Compositor config language. `conf` (hyprlang) is the revert path only -- it warns on 0.56 and stops being read in 0.57.";
    };

    monitor = mkOption {
      type = types.str;
      default = "Virtual-1,preferred,auto,1";
      description = "Monitor as the hyprlang `output,mode,position,scale` line. Pinned because virtio-gpu reports no EDID, so there is no mode list to negotiate.";
    };

    terminal = mkOption {
      type = types.str;
      default = "alacritty";
      description = "Terminal launched by the Hyprland keybind. Alacritty (GL 3.3) renders on virgl; Ghostty >= 1.2 needs GL 4.3, which Parallels does not give Linux guests.";
    };

    extraExecOnce = mkOption {
      type = types.listOf types.str;
      default = [ ];
      description = "Extra commands run once at compositor start. Lets guest/hardware modules add session autostarts without this module knowing about them.";
    };
  };

  config = {
    assertions = [
      {
        assertion = length monitorFields == 4;
        message = "modules.nixos.desktop.monitor must be `output,mode,position,scale`; got ${cfg.monitor}";
      }
    ];

    # Hyprland 0.56 ships no systemd session target, so define the one the
    # exec-once above starts. Binding graphical-session.target lets user units
    # WantedBy it (wayvnc) start with the compositor and stop with it.
    systemd.user.targets.hyprland-session = {
      unitConfig = {
        Description = "Hyprland compositor session";
        Documentation = [ "man:systemd.special(7)" ];
        BindsTo = [ "graphical-session.target" ];
        Wants = [ "graphical-session-pre.target" ];
        After = [ "graphical-session-pre.target" ];
      };
    };

    programs.hyprland.enable = true;

    services.greetd = {
      enable = true;
      settings.default_session = {
        command = "${lib.getExe pkgs.tuigreet} --time --remember --cmd ${config.programs.hyprland.package}/bin/start-hyprland";
        user = "greeter";
      };
    };

    security.rtkit.enable = true;
    services.pipewire = {
      enable = true;
      alsa.enable = true;
      pulse.enable = true;
    };

    # config/alacritty/alacritty.toml asks for this family by name.
    fonts.packages = [ pkgs.nerd-fonts.jetbrains-mono ];

    environment.systemPackages = with pkgs; [
      # home/shell/alacritty.nix ships config only (the binary comes from the
      # distro on the other Linux hosts), so NixOS has to provide the binary.
      alacritty
      waybar
      mako
      fuzzel
      wl-clipboard
      mesa-demos # glxinfo -B is the GPU acceptance check
    ];

    # /etc/xdg is the last stop in hyprutils' config search, so a user config
    # of the same format still wins if one is created.
    environment.etc =
      if cfg.configFormat == "lua" then
        { "xdg/hypr/hyprland.lua".text = luaConfig; }
      else
        { "xdg/hypr/hyprland.conf".text = confConfig; };
  };
}
