# modules/nixos/desktop-hyprland.nix -- minimal declarative Hyprland desktop
#
# Deliberately small: greetd -> Hyprland, PipeWire, a bar, a notifier, a
# launcher and a terminal. The Omarchy tracked-input port is its own later
# phase and will replace most of this.
#
# The compositor config is written to /etc/xdg/hypr/hyprland.conf, the last
# fallback in hyprutils' config search (XDG_CONFIG_HOME -> ~/.config ->
# XDG_CONFIG_DIRS -> /etc/xdg), so a user config still wins if one is created.

{
  lib,
  config,
  pkgs,
  ...
}:

with lib;
let
  cfg = config.modules.nixos.desktop;
in
{
  options.modules.nixos.desktop = {
    monitor = mkOption {
      type = types.str;
      default = "Virtual-1,preferred,auto,1";
      description = "Hyprland `monitor=` line. Pinned because virtio-gpu reports no EDID, so there is no mode list to negotiate.";
    };

    terminal = mkOption {
      type = types.str;
      default = "alacritty";
      description = "Terminal launched by the Hyprland keybind. Alacritty (GL 3.3) renders on virgl; Ghostty >= 1.2 needs GL 4.3, which Parallels does not give Linux guests.";
    };
  };

  config = {
    programs.hyprland.enable = true;

    services.greetd = {
      enable = true;
      settings.default_session = {
        command = "${lib.getExe pkgs.tuigreet} --time --remember --cmd ${config.programs.hyprland.package}/bin/Hyprland";
        user = "greeter";
      };
    };

    security.rtkit.enable = true;
    services.pipewire = {
      enable = true;
      alsa.enable = true;
      pulse.enable = true;
    };

    # config/alacritty/alacritty.toml asks for this family by name.
    fonts.packages = [ pkgs.nerd-fonts.jetbrains-mono ];

    environment.systemPackages = with pkgs; [
      # home/shell/alacritty.nix ships config only (the binary comes from the
      # distro on the other Linux hosts), so NixOS has to provide the binary.
      alacritty
      waybar
      mako
      fuzzel
      wl-clipboard
      mesa-demos # glxinfo -B is the GPU acceptance check
    ];

    environment.etc."xdg/hypr/hyprland.conf".text = ''
      # Generated by modules/nixos/desktop-hyprland.nix -- copy to
      # ~/.config/hypr/hyprland.conf to take it over.
      monitor = ${cfg.monitor}

      cursor {
        # aquamarine ignores WLR_NO_HARDWARE_CURSORS; this is the replacement.
        no_hardware_cursors = true
      }

      exec-once = waybar
      exec-once = mako

      $mod = SUPER
      bind = $mod, Return, exec, ${cfg.terminal}
      bind = $mod, D, exec, fuzzel
      bind = $mod, Q, killactive
      bind = $mod SHIFT, E, exit
    '';
  };
}
