import re
from dataclasses import dataclass
from pathlib import Path

import frontmatter

from kb_engine.models import Area, Topic, TopicMember
from kb_engine.store import Store

PROPOSALS_START = "<!-- KB-PROPOSALS:START -->"
PROPOSALS_END = "<!-- KB-PROPOSALS:END -->"

_TOPICS_RELDIR = Path("_system") / "topics"
_TAXONOMY_RELPATH = Path("_system") / "_taxonomy.md"
_TOPIC_LINK_PREFIX = "_system/topics"


@dataclass(frozen=True)
class RenderResult:
    n_topics: int
    n_areas: int
    index_path: str  # vault-relative posix
    topic_paths: tuple[str, ...]  # vault-relative posix
    taxonomy_path: str  # vault-relative posix
    unfiled_path: str  # vault-relative posix


def _topics_by_slug(topics: list[Topic]) -> dict[str, Topic]:
    return {topic.slug: topic for topic in topics}


def _render_index(
    areas: list[Area],
    topics: list[Topic],
    members_by_slug: dict[str, list[TopicMember]],
) -> str:
    """Render the areas→topics outline. Deterministic (no timestamps)."""
    by_slug = _topics_by_slug(topics)
    lines: list[str] = ["# Topics", ""]

    def topic_line(slug: str) -> str:
        topic = by_slug[slug]
        count = len(members_by_slug.get(slug, []))
        return (
            f"- [[{_TOPIC_LINK_PREFIX}/{slug}]] — {topic.label} "
            f"({count} notes) [{topic.kind}/{topic.status}]"
        )

    grouped: set[str] = set()
    for area in areas:
        area_slugs = [slug for slug in area.topic_slugs if slug in by_slug]
        if not area_slugs:
            continue
        lines.append(f"## {area.label}")
        for slug in sorted(area_slugs):
            lines.append(topic_line(slug))
            grouped.add(slug)
        lines.append("")

    ungrouped = sorted(slug for slug in by_slug if slug not in grouped)
    if ungrouped:
        lines.append("## Ungrouped")
        for slug in ungrouped:
            lines.append(topic_line(slug))
        lines.append("")

    body = "\n".join(lines).rstrip() + "\n"
    post = frontmatter.Post(body, type="system", generated=True)
    return frontmatter.dumps(post) + "\n"


def _render_topic_moc(topic: Topic, members: list[TopicMember]) -> str:
    """Render one topic MOC, splitting primary (home) from secondary members.

    Primary members are listed under ``## Notes``; secondary (cross-link) members
    under ``## Also relevant``. A section is omitted when it has no members, so an
    all-secondary topic shows no empty ``## Notes`` placeholder; a topic with no
    members at all still gets a ``## Notes`` section. Each section is sorted by
    score desc, then path, for deterministic output.
    """
    keywords = ", ".join(topic.keywords)
    lines = [
        f"# {topic.label}",
        "",
        f"- slug: `{topic.slug}`",
        f"- kind/status: {topic.kind}/{topic.status}",
        f"- keywords: {keywords}",
        "",
    ]

    def block(header: str, items: list[TopicMember]) -> None:
        lines.extend([header, ""])
        ordered = sorted(items, key=lambda m: (-m.score, m.note_path))
        if ordered:
            lines.extend(f"- [[{m.note_path}]] ({m.score:.2f})" for m in ordered)
        else:
            lines.append("_None._")
        lines.append("")

    primary = [m for m in members if m.is_primary]
    secondary = [m for m in members if not m.is_primary]
    if primary:
        block("## Notes", primary)
    if secondary:
        block("## Also relevant", secondary)
    if not primary and not secondary:
        # A topic with no members at all still gets a Notes section placeholder.
        block("## Notes", [])

    body = "\n".join(lines).rstrip() + "\n"
    post = frontmatter.Post(body, type="system", generated=True)
    return frontmatter.dumps(post) + "\n"


def _render_unfiled_by_category(by_note: dict[str, list[str]]) -> str:
    """Group topicless notes under each taxonomy tag (a note may appear under several)."""
    by_tag: dict[str, list[str]] = {}
    for note_path, tags in by_note.items():
        for tag in (tags or ["(untagged)"]):
            by_tag.setdefault(tag, []).append(note_path)
    lines = [
        "# Unfiled by Category",
        "",
        "_Notes in no topic, grouped by taxonomy tag._",
        "",
    ]
    for tag in sorted(by_tag):
        lines.append(f"## {tag}")
        for note_path in sorted(by_tag[tag]):
            lines.append(f"- [[{note_path}]]")
        lines.append("")
    body = "\n".join(lines).rstrip() + "\n"
    return frontmatter.dumps(frontmatter.Post(body, type="system", generated=True)) + "\n"


def _render_proposals_block(
    topics: list[Topic], members_by_slug: dict[str, list[TopicMember]]
) -> str:
    """Render the proposals table body (between markers, excluding the markers)."""
    proposed = sorted(
        (t for t in topics if t.kind == "discovered" and t.status == "proposed"),
        key=lambda t: t.slug,
    )
    lines = [
        "_Discovered topics awaiting review. Regenerated by `kb-engine topics render`._",
        "",
        "| Slug | Keywords | Size |",
        "|------|----------|------|",
    ]
    for topic in proposed:
        keywords = ", ".join(topic.keywords)
        size = len(members_by_slug.get(topic.slug, []))
        lines.append(f"| {topic.slug} | {keywords} | {size} |")
    return "\n".join(lines)


def _strip_markers(text: str) -> str:
    """Remove every stray START/END marker line, collapsing the blank gap left.

    Used to recover from a malformed taxonomy (lone, out-of-order, or duplicate
    markers) before a clean block is re-appended.
    """
    stripped = re.sub(
        rf"[ \t]*(?:{re.escape(PROPOSALS_START)}|{re.escape(PROPOSALS_END)})[ \t]*\n?",
        "",
        text,
    )
    return re.sub(r"\n{3,}", "\n\n", stripped)


def _splice_proposals(existing_text: str, block_body: str) -> str:
    """Replace content between the proposal markers, preserving the rest.

    Only a *well-formed* pair (a START followed by an END) is spliced in place.
    Any malformed state — lone marker, END-before-START, or duplicates — is
    repaired by stripping every stray marker, then appending a single fresh
    block. This keeps the result a single well-formed block and idempotent.
    """
    marked = f"{PROPOSALS_START}\n{block_body}\n{PROPOSALS_END}"
    start = existing_text.find(PROPOSALS_START)
    end = existing_text.find(PROPOSALS_END)
    well_formed = (
        start != -1
        and end != -1
        and start < end
        and existing_text.count(PROPOSALS_START) == 1
        and existing_text.count(PROPOSALS_END) == 1
    )
    if well_formed:
        pattern = re.compile(
            re.escape(PROPOSALS_START) + r".*?" + re.escape(PROPOSALS_END),
            re.DOTALL,
        )
        return pattern.sub(lambda _: marked, existing_text, count=1)

    base = _strip_markers(existing_text).rstrip("\n")
    section = f"## Proposals\n\n{marked}\n"
    if base:
        return f"{base}\n\n{section}"
    return section


def _write_proposals(
    taxonomy_path: Path,
    topics: list[Topic],
    members_by_slug: dict[str, list[TopicMember]],
) -> None:
    block_body = _render_proposals_block(topics, members_by_slug)
    if taxonomy_path.exists():
        existing = taxonomy_path.read_text()
    else:
        existing = "# Knowledge Base Taxonomy\n"
    taxonomy_path.write_text(_splice_proposals(existing, block_body))


def render_topics(store: Store, vault_path: Path) -> RenderResult:
    """Render topic/area MOCs to ``_system/topics/`` + proposals into ``_taxonomy.md``.

    Render-not-append and idempotent: bodies contain no timestamps, members are
    deterministically ordered, and the proposal block is spliced between stable
    markers (preserving the rest of ``_taxonomy.md``). ``_system/topics/`` lives
    outside ``Knowledge/`` so these files are never embedded.
    """
    topics = store.load_topics()
    areas = store.load_areas()
    members_by_slug = {
        topic.slug: store.topic_members(topic.slug) for topic in topics
    }

    vault_resolved = vault_path.resolve()
    topics_dir = vault_path / _TOPICS_RELDIR
    topics_dir.mkdir(parents=True, exist_ok=True)
    topics_dir_resolved = topics_dir.resolve()

    index_path = topics_dir / "index.md"
    index_path.write_text(_render_index(areas, topics, members_by_slug))

    topic_paths: list[str] = []
    for topic in topics:
        moc_path = (topics_dir / f"{topic.slug}.md").resolve()
        # Defense-in-depth: a malicious slug (bypassing input validation) must
        # never write outside _system/topics/. Skip rather than write.
        if not moc_path.is_relative_to(topics_dir_resolved):
            continue
        moc_path.write_text(
            _render_topic_moc(topic, members_by_slug.get(topic.slug, []))
        )
        # Vault-relative posix (Phase 3 contract: consistent with note paths).
        topic_paths.append(moc_path.relative_to(vault_resolved).as_posix())

    unfiled_relpath = _TOPICS_RELDIR / "_unfiled-by-category.md"
    (topics_dir / "_unfiled-by-category.md").write_text(
        _render_unfiled_by_category(store.notes_without_topic())
    )

    taxonomy_path = vault_path / _TAXONOMY_RELPATH
    taxonomy_path.parent.mkdir(parents=True, exist_ok=True)
    _write_proposals(taxonomy_path, topics, members_by_slug)

    return RenderResult(
        n_topics=len(topics),
        n_areas=len(areas),
        index_path=_TOPICS_RELDIR.joinpath("index.md").as_posix(),
        topic_paths=tuple(topic_paths),
        taxonomy_path=_TAXONOMY_RELPATH.as_posix(),
        unfiled_path=unfiled_relpath.as_posix(),
    )
