import re
from dataclasses import dataclass
from pathlib import Path

import frontmatter

from kb_engine.models import Area, Topic, TopicMember
from kb_engine.store import Store

PROPOSALS_START = "<!-- KB-PROPOSALS:START -->"
PROPOSALS_END = "<!-- KB-PROPOSALS:END -->"

_TOPICS_RELDIR = Path("_system") / "topics"
_TAXONOMY_RELPATH = Path("_system") / "_taxonomy.md"
_TOPIC_LINK_PREFIX = "_system/topics"


@dataclass(frozen=True)
class RenderResult:
    n_topics: int
    n_areas: int
    index_path: str
    topic_paths: list[str]
    taxonomy_path: str


def _topics_by_slug(topics: list[Topic]) -> dict[str, Topic]:
    return {topic.slug: topic for topic in topics}


def _render_index(
    areas: list[Area],
    topics: list[Topic],
    members_by_slug: dict[str, list[TopicMember]],
) -> str:
    """Render the areas→topics outline. Deterministic (no timestamps)."""
    by_slug = _topics_by_slug(topics)
    lines: list[str] = ["# Topics", ""]

    def topic_line(slug: str) -> str:
        topic = by_slug[slug]
        count = len(members_by_slug.get(slug, []))
        return (
            f"- [[{_TOPIC_LINK_PREFIX}/{slug}]] — {topic.label} "
            f"({count} notes) [{topic.kind}/{topic.status}]"
        )

    grouped: set[str] = set()
    for area in areas:
        area_slugs = [slug for slug in area.topic_slugs if slug in by_slug]
        if not area_slugs:
            continue
        lines.append(f"## {area.label}")
        for slug in sorted(area_slugs):
            lines.append(topic_line(slug))
            grouped.add(slug)
        lines.append("")

    ungrouped = sorted(slug for slug in by_slug if slug not in grouped)
    if ungrouped:
        lines.append("## Ungrouped")
        for slug in ungrouped:
            lines.append(topic_line(slug))
        lines.append("")

    body = "\n".join(lines).rstrip() + "\n"
    post = frontmatter.Post(body, type="system", generated=True)
    return frontmatter.dumps(post) + "\n"


def _render_topic_moc(
    topic: Topic, members: list[TopicMember]
) -> str:
    """Render one topic MOC. Members sorted by score desc, then path."""
    keywords = ", ".join(topic.keywords)
    lines = [
        f"# {topic.label}",
        "",
        f"- slug: `{topic.slug}`",
        f"- kind/status: {topic.kind}/{topic.status}",
        f"- keywords: {keywords}",
        "",
        "## Notes",
        "",
    ]
    ordered = sorted(members, key=lambda m: (-m.score, m.note_path))
    if ordered:
        for member in ordered:
            lines.append(f"- [[{member.note_path}]] ({member.score:.2f})")
    else:
        lines.append("_No member notes._")

    body = "\n".join(lines).rstrip() + "\n"
    post = frontmatter.Post(body, type="system", generated=True)
    return frontmatter.dumps(post) + "\n"


def _render_proposals_block(
    topics: list[Topic], members_by_slug: dict[str, list[TopicMember]]
) -> str:
    """Render the proposals table body (between markers, excluding the markers)."""
    proposed = sorted(
        (t for t in topics if t.kind == "discovered" and t.status == "proposed"),
        key=lambda t: t.slug,
    )
    lines = [
        "_Discovered topics awaiting review. Regenerated by `kb-engine topics render`._",
        "",
        "| Slug | Keywords | Size |",
        "|------|----------|------|",
    ]
    for topic in proposed:
        keywords = ", ".join(topic.keywords)
        size = len(members_by_slug.get(topic.slug, []))
        lines.append(f"| {topic.slug} | {keywords} | {size} |")
    return "\n".join(lines)


def _splice_proposals(existing_text: str, block_body: str) -> str:
    """Replace content between the proposal markers, preserving the rest.

    If both markers are present, only the text between them is replaced. If they
    are absent, a ``## Proposals`` section with the marker block is appended.
    """
    marked = f"{PROPOSALS_START}\n{block_body}\n{PROPOSALS_END}"
    if PROPOSALS_START in existing_text and PROPOSALS_END in existing_text:
        pattern = re.compile(
            re.escape(PROPOSALS_START) + r".*?" + re.escape(PROPOSALS_END),
            re.DOTALL,
        )
        return pattern.sub(lambda _: marked, existing_text, count=1)
    base = existing_text.rstrip("\n")
    section = f"## Proposals\n\n{marked}\n"
    if base:
        return f"{base}\n\n{section}"
    return section


def _write_proposals(
    taxonomy_path: Path,
    topics: list[Topic],
    members_by_slug: dict[str, list[TopicMember]],
) -> None:
    block_body = _render_proposals_block(topics, members_by_slug)
    if taxonomy_path.exists():
        existing = taxonomy_path.read_text()
    else:
        existing = "# Knowledge Base Taxonomy\n"
    taxonomy_path.write_text(_splice_proposals(existing, block_body))


def render_topics(store: Store, vault_path: Path) -> RenderResult:
    """Render topic/area MOCs to ``_system/topics/`` + proposals into ``_taxonomy.md``.

    Render-not-append and idempotent: bodies contain no timestamps, members are
    deterministically ordered, and the proposal block is spliced between stable
    markers (preserving the rest of ``_taxonomy.md``). ``_system/topics/`` lives
    outside ``Knowledge/`` so these files are never embedded.
    """
    topics = store.load_topics()
    areas = store.load_areas()
    members_by_slug = {
        topic.slug: store.topic_members(topic.slug) for topic in topics
    }

    topics_dir = vault_path / _TOPICS_RELDIR
    topics_dir.mkdir(parents=True, exist_ok=True)

    index_path = topics_dir / "index.md"
    index_path.write_text(_render_index(areas, topics, members_by_slug))

    topic_paths: list[str] = []
    for topic in topics:
        moc_path = topics_dir / f"{topic.slug}.md"
        moc_path.write_text(
            _render_topic_moc(topic, members_by_slug.get(topic.slug, []))
        )
        topic_paths.append(str(moc_path))

    taxonomy_path = vault_path / _TAXONOMY_RELPATH
    taxonomy_path.parent.mkdir(parents=True, exist_ok=True)
    _write_proposals(taxonomy_path, topics, members_by_slug)

    return RenderResult(
        n_topics=len(topics),
        n_areas=len(areas),
        index_path=str(index_path),
        topic_paths=topic_paths,
        taxonomy_path=str(taxonomy_path),
    )
